<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vijay-CH" name="com.staff.qa.testcases.PlacementPageTest" tests="37" failures="5" timestamp="26 Nov 2019 06:03:37 GMT" time="1655.181" errors="0">
  <testcase name="verifyUserNavigateToConsultantPage" time="16.056" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="VerifyAllPlacementCountInHeaderAndGrid" time="27.240" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="VerifyOpenPlacementCountInHeaderAndGrid" time="26.793" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="VerifyPendingApprovalPlacementCountInHeaderAndGrid" time="29.079" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="VerifyApprovedPlacementCountInHeaderAndGrid" time="29.748" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="VerifyCandidateOnBillingPlacementCountInHeaderAndGrid" time="29.247" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="VerifyBackedOutPlacementCountInHeaderAndGrid" time="28.923" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="VerifyCandidateEndedPlacementCountInHeaderAndGrid" time="30.067" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyPlacedConsultantAppearInPlacement_FromRequirement" time="98.227" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyPlacedConsultantAppearInPlacement_FromConsultant" time="94.935" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyBackedOutConsultantFunctionality" time="61.870" classname="com.staff.qa.testcases.PlacementPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.PlacementPageTest.verifyBackedOutConsultantFunctionality(PlacementPageTest.java:524)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyBackedOutConsultantFunctionality -->
  <testcase name="verifyBackedOutFilterData" time="30.507" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyOpenFilterData" time="36.087" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyPendingApprovalFilterData" time="30.032" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyApprovedFilterData" time="31.692" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyCandidateOnBillingFilterData" time="32.616" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyCandidateEndedFilterData" time="30.924" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyAddNoteFunctionality" time="34.589" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyCancelBtnFunOfAddNote" time="34.331" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyDownloadPlacementFormFunctionality" time="28.764" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyEditClientAssignmentFieldsOfPlacementFormFunctionality" time="71.340" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyEditConsultantDetailsOfPlacementFormFunctionality" time="58.012" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyEditGrossMarginOfPlacementFormFunctionality" time="37.917" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyCancelButtonFunGrossMarginOfPlacementForm" time="37.156" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyCancelButtonFunConsultantDetailsOfPlacementForm" time="36.911" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyCancelButtonFunClientAssignmentOfPlacementForm" time="36.121" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyCompaniesSearchTextBoxFunOfPlacementForm" time="19.455" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyCompaniesFilterFunOfPlacementForm" time="19.399" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyCompaniesFilterFunOfPlacementForm1" time="41.308" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyAccountManagerSearchTextBoxFunOfPlacementForm" time="34.123" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyAccountMangerFilterFunOfPlacementForm" time="20.151" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyAccountManagerFilterFunOfPlacementForm1" time="40.535" classname="com.staff.qa.testcases.PlacementPageTest">
    <failure type="java.lang.AssertionError" message="expected [Open Placements (329)] but found [Open Placements (4)]">
      <![CDATA[java.lang.AssertionError: expected [Open Placements (329)] but found [Open Placements (4)]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.staff.qa.testcases.PlacementPageTest.verifyAccountManagerFilterFunOfPlacementForm1(PlacementPageTest.java:1521)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyAccountManagerFilterFunOfPlacementForm1 -->
  <testcase name="verifyPlacementDateFilterFunOfPlacementForm" time="58.386" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyInitiateOfferFunctionality" time="162.999" classname="com.staff.qa.testcases.PlacementPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.PlacementPageTest.verifyInitiateOfferFunctionality(PlacementPageTest.java:1832)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyInitiateOfferFunctionality -->
  <testcase name="verifySubmitForApprovalFunctionality1" time="95.805" classname="com.staff.qa.testcases.PlacementPageTest">
    <failure type="java.lang.AssertionError" message="expected [Placement Details of Consultant Details section for &#039;John John&#039; Updated Successfully] but found [Placement submitted for approval successfully for consultant : John John]">
      <![CDATA[java.lang.AssertionError: expected [Placement Details of Consultant Details section for 'John John' Updated Successfully] but found [Placement submitted for approval successfully for consultant : John John]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.staff.qa.testcases.PlacementPageTest.verifySubmitForApprovalFunctionality1(PlacementPageTest.java:2158)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifySubmitForApprovalFunctionality1 -->
  <testcase name="verifyApprovePlacementFunctionality_Validations" time="49.909" classname="com.staff.qa.testcases.PlacementPageTest"/>
  <testcase name="verifyRejectPlacementFunctionality_Validations" time="73.927" classname="com.staff.qa.testcases.PlacementPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.PlacementPageTest.verifyRejectPlacementFunctionality_Validations(PlacementPageTest.java:2478)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyRejectPlacementFunctionality_Validations -->
</testsuite> <!-- com.staff.qa.testcases.PlacementPageTest -->
