<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vijay-CH" name="com.staff.qa.testcases.RequirementPageTest" tests="24" failures="3" timestamp="14 Oct 2019 09:56:14 GMT" time="888.938" errors="0">
  <testcase name="verifyAddRequirementFunctionality" time="66.012" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyEditRequirementFunctionality" time="65.555" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyUploadDocumentFunctionality" time="31.484" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyUploadDocumentAppearInGrid" time="32.332" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyDownloadUploadedDocument_requirement" time="23.486" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyCancelBtnFunOfUploadDocPopUp_requirement" time="21.623" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyEditJobDescriptionFunctionality" time="29.076" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyArchivedRequirementFunctionality" time="47.384" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyUnArchivedRequirementFunctionality" time="33.397" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyValidationMessageForClosuredate" time="40.918" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyValidationMessageForClosureReason" time="43.655" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyCancelButtonFunctionalityOfArchiveRequirementPopUp" time="32.238" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyValidationsForAddNewRequirement" time="12.291" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyConsultantMapToRequirement" time="43.022" classname="com.staff.qa.testcases.RequirementPageTest">
    <failure type="java.lang.AssertionError" message="expected [Sanaz Afshar] but found [Don DeCosta]">
      <![CDATA[java.lang.AssertionError: expected [Sanaz Afshar] but found [Don DeCosta]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.staff.qa.testcases.RequirementPageTest.verifyConsultantMapToRequirement(RequirementPageTest.java:845)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyConsultantMapToRequirement -->
  <testcase name="verifyConsultantMapToRequirement_alreadyExists" time="40.411" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyArchivedConsultantMapToRequirement" time="36.757" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyCancelBtnFunOfMapConsultantWindow" time="43.406" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyAddNoteFunctionality" time="27.841" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyCancelBtnFunOfAddNote" time="28.560" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyNavigateToStatusPopUp" time="50.857" classname="com.staff.qa.testcases.RequirementPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.RequirementPageTest.verifyNavigateToStatusPopUp(RequirementPageTest.java:1105)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyNavigateToStatusPopUp -->
  <testcase name="verifySetTheStatusToConsultant" time="36.363" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyCancelButtonFunOfSetStatusPopUp" time="45.324" classname="com.staff.qa.testcases.RequirementPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.RequirementPageTest.verifyCancelButtonFunOfSetStatusPopUp(RequirementPageTest.java:1198)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyCancelButtonFunOfSetStatusPopUp -->
  <testcase name="verifyDeleteRecentStatusFunctionality" time="30.535" classname="com.staff.qa.testcases.RequirementPageTest"/>
  <testcase name="verifyViewResumeFunctionality" time="26.411" classname="com.staff.qa.testcases.RequirementPageTest"/>
</testsuite> <!-- com.staff.qa.testcases.RequirementPageTest -->
