<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vijay-CH" name="com.staff.qa.testcases.LoginPageTest" tests="9" failures="1" timestamp="07 Oct 2019 05:01:20 GMT" time="80.915" errors="0">
  <testcase name="validateLoginFunctionalityForIncorrectUserNamePassword" time="9.933" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validateUsernameMessageForIncorrectUsername" time="8.262" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="loginPageTitleTest" time="6.501" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validatePasswordMessageForBlankPassword" time="8.263" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validateMessageForBlankUsernamePassword" time="8.553" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validatePasswordMessageForIncorrectPassword" time="8.156" classname="com.staff.qa.testcases.LoginPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.staff.qa.testcases.LoginPageTest.validatePasswordMessageForIncorrectPassword(LoginPageTest.java:210)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validatePasswordMessageForIncorrectPassword -->
  <testcase name="validateUsernameMessageForBalankUsername" time="14.668" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="validateMessageForBlankPasswordIncorrectUsername" time="8.290" classname="com.staff.qa.testcases.LoginPageTest"/>
  <testcase name="loginTest" time="8.289" classname="com.staff.qa.testcases.LoginPageTest"/>
</testsuite> <!-- com.staff.qa.testcases.LoginPageTest -->
